# Generated by Django 6.0.1 on 2026-02-14 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 10, 35, 13, 500476)),
        ),
    ]
