# Generated by Django 6.0.1 on 2026-02-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
