# Generated by Django 6.0.1 on 2026-02-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
